server {
    listen 80;
    listen [::]:80;
    server_name __DOMAIN__ www.__DOMAIN__;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }

    include snippets/emostr-locations.conf;
}
