location = /curl {
    root __APP_DIR__/current/public;
    types { }
    default_type "text/plain; charset=utf-8";
    include snippets/emostr-headers.conf;
    add_header Cache-Control "no-store";
    add_header Vary "User-Agent";
    try_files /curl =404;
}
